# Generated by Django 5.0.9 on 2026-04-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("device_id", models.AutoField(primary_key=True, serialize=False)),
                ("name_dev", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "device",
            },
        ),
    ]
