# Generated by Django 5.0.9 on 2026-04-25 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actuator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actuator_type",
                    models.CharField(
                        choices=[
                            ("LED", "LED"),
                            ("buzzer", "Buzzer"),
                            ("relay", "Relay"),
                            ("motor", "Motor"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actuator_name", models.CharField(max_length=100)),
                ("gpio_pin", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "current_status",
                    models.CharField(
                        choices=[("on", "On"), ("off", "Off"), ("error", "Error")],
                        default="off",
                        max_length=20,
                    ),
                ),
                (
                    "operation_mode",
                    models.CharField(
                        choices=[("manual", "Manual"), ("automatic", "Automatic")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "actuators",
            },
        ),
        migrations.CreateModel(
            name="IoTNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_name", models.CharField(max_length=100)),
                ("hardware_type", models.CharField(max_length=50)),
                ("mac_address", models.CharField(max_length=17, unique=True)),
                ("local_ip", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "firmware_version",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("error", "Error"),
                        ],
                        default="disconnected",
                        max_length=20,
                    ),
                ),
                ("last_connection", models.DateTimeField(blank=True, null=True)),
                ("installation_date", models.DateField()),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iot_nodes",
                        to="core.homezone",
                    ),
                ),
            ],
            options={
                "db_table": "iot_nodes",
            },
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("LDR", "LDR"),
                            ("PIR", "PIR"),
                            ("DHT11", "DHT11"),
                            ("MQ2", "MQ2"),
                            ("ultrasonic", "Ultrasonic"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sensor_name", models.CharField(max_length=100)),
                ("gpio_pin", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "measurement_unit",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "minimum_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "maximum_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensors",
                        to="devices.iotnode",
                    ),
                ),
            ],
            options={
                "db_table": "sensors",
            },
        ),
        migrations.DeleteModel(
            name="Device",
        ),
        migrations.AddField(
            model_name="actuator",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actuators",
                to="devices.iotnode",
            ),
        ),
    ]
