# Generated by Django 5.0.9 on 2026-04-25 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlarmStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("armed", "Armed"),
                            ("disarmed", "Disarmed"),
                            ("triggered", "Triggered"),
                            ("silenced", "Silenced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("change_timestamp", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "access_code_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "alarm_statuses",
            },
        ),
        migrations.CreateModel(
            name="AutomationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_name", models.CharField(max_length=150)),
                (
                    "condition_operator",
                    models.CharField(
                        choices=[
                            ("<", "<"),
                            (">", ">"),
                            ("=", "="),
                            (">=", ">="),
                            ("<=", "<="),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "condition_value",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("turn_on", "Turn On"),
                            ("turn_off", "Turn Off"),
                            ("toggle", "Toggle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "automation_settings",
            },
        ),
        migrations.CreateModel(
            name="CommandResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_timestamp", models.DateTimeField(auto_now_add=True)),
                ("was_successful", models.BooleanField()),
                (
                    "response_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "resulting_actuator_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "command_responses",
            },
        ),
        migrations.CreateModel(
            name="LightingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("on", "On"), ("off", "Off"), ("dimmed", "Dimmed")],
                        max_length=20,
                    ),
                ),
                (
                    "intensity_percentage",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("change_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "change_source",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic"),
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "lighting_statuses",
            },
        ),
        migrations.CreateModel(
            name="RemoteCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command_type", models.CharField(max_length=50)),
                ("json_parameters", models.JSONField(blank=True, null=True)),
                ("sent_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "sending_channel",
                    models.CharField(
                        choices=[
                            ("REST_API", "REST API"),
                            ("MQTT", "MQTT"),
                            ("mobile_app", "Mobile App"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sending_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "remote_commands",
            },
        ),
    ]
