# Generated by Django 5.0.9 on 2026-04-25 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("automation", "0001_initial"),
        ("core", "0001_initial"),
        ("devices", "0002_actuator_iotnode_sensor_delete_device_actuator_node"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmstatus",
            name="home",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarm_statuses",
                to="core.home",
            ),
        ),
        migrations.AddField(
            model_name="alarmstatus",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alarm_changes",
                to="users.appuser",
            ),
        ),
        migrations.AddField(
            model_name="automationsetting",
            name="action_actuator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automation_actions",
                to="devices.actuator",
            ),
        ),
        migrations.AddField(
            model_name="automationsetting",
            name="condition_sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automation_conditions",
                to="devices.sensor",
            ),
        ),
        migrations.AddField(
            model_name="automationsetting",
            name="home",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automation_settings",
                to="core.home",
            ),
        ),
        migrations.AddField(
            model_name="lightingstatus",
            name="actuator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lighting_statuses",
                to="devices.actuator",
            ),
        ),
        migrations.AddField(
            model_name="lightingstatus",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lighting_changes",
                to="users.appuser",
            ),
        ),
        migrations.AddField(
            model_name="lightingstatus",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lighting_statuses",
                to="core.homezone",
            ),
        ),
        migrations.AddField(
            model_name="remotecommand",
            name="actuator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="remote_commands",
                to="devices.actuator",
            ),
        ),
        migrations.AddField(
            model_name="remotecommand",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="remote_commands",
                to="users.appuser",
            ),
        ),
        migrations.AddField(
            model_name="commandresponse",
            name="command",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response",
                to="automation.remotecommand",
            ),
        ),
    ]
