# Generated by Django 5.0.9 on 2026-04-25 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(default="Colombia", max_length=100)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "homes",
            },
        ),
        migrations.CreateModel(
            name="MotionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_timestamp", models.DateTimeField(auto_now_add=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "confidence_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "motion_events",
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=10)),
                ("text_value", models.CharField(blank=True, max_length=50, null=True)),
                ("reading_timestamp", models.DateTimeField(auto_now_add=True)),
                ("signal_quality", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "sensor_readings",
            },
        ),
        migrations.CreateModel(
            name="SystemAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("motion", "Motion"),
                            ("luminosity", "Luminosity"),
                            ("connection", "Connection"),
                            ("hardware", "Hardware"),
                            ("security", "Security"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("alert_timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolution_timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "system_alerts",
            },
        ),
        migrations.CreateModel(
            name="HomeZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("floor_number", models.IntegerField(default=1)),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="core.home",
                    ),
                ),
            ],
            options={
                "db_table": "home_zones",
            },
        ),
    ]
