# Generated by Django 5.0.9 on 2026-04-25 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("devices", "0002_actuator_iotnode_sensor_delete_device_actuator_node"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="motionevent",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="motion_events",
                to="devices.sensor",
            ),
        ),
        migrations.AddField(
            model_name="motionevent",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="motion_events",
                to="core.homezone",
            ),
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="readings",
                to="devices.sensor",
            ),
        ),
        migrations.AddField(
            model_name="systemalert",
            name="home",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="core.home",
            ),
        ),
        migrations.AddField(
            model_name="systemalert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alerts",
                to="users.appuser",
            ),
        ),
        migrations.AddField(
            model_name="systemalert",
            name="sensor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="devices.sensor",
            ),
        ),
    ]
